# Everything you need to know about configuring the CMS can be found here:-
# https://www.netlifycms.org/docs/configuration-options/

backend:
  name: git-gateway # Netlify’s Git Gateway connects to Git provider’s API
  branch: master # Branch to update (master by default)

media_folder: "assets/images/uploads" # Folder where user uploaded files should go

publish_mode: editorial_workflow # Enable drafts

collections: # A list of collections the CMS should be able to edit
  # POSTS
  - name: "post" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Post" # Used in the UI, ie.: "New Post"
    folder: "_posts" # The path to the folder where the documents are stored
    sort: "date:desc" # Default is title:asc
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields: # The fields each document in this collection have
      - {label: "Layout", name: "layout", widget: "hidden", default: "post"}
      - {label: "Title", name: "title", widget: "string", tagname: "h1"}
      - {label: "Slug", name: "ref", widget: "string"}
      - label: "Language"
        name: "lang"
        widget: "select"
        options:
          - { label: "Italiano", value: "it" }
          - { label: "Inglese", value: "en" }
      - {label: "Publish Date", name: "date", widget: "datetime", format: "YYYY-MM-DD HH:mm:ss"}
      - {label: "Body", name: "body", widget: "markdown", required: false}
      - {label: "Categories", name: "categories", widget: "string", required: false}
